version: '3.8'

services:
   web:
      tty: true
      stdin_open: true
      build:
         context: '.'
         dockerfile: ./docker/prod.Dockerfile
      ports:
         - 80:3000
      restart: always

   mysql:
      image: mysql:5.7
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: dbuser
         MYSQL_PASSWORD: dbpass
         MYSQL_DATABASE: picture-shop
      volumes:
         - mysql:/var/lib/mysql
      command: mysqld --innodb_use_native_aio=0
      ports:
         - '3307:3306'
      healthcheck:
         test: ['CMD', 'mysqladmin', 'ping', '-proot']
         interval: 1m30s
         timeout: 10s
         retries: 3
         start_period: 10s
      restart: always

volumes:
   mysql:
