version: '3.8'

services:
   web:
      tty: true
      stdin_open: true
      build:
         context: '.'
         dockerfile: ./docker/Dockerfile
         target: base
      command: sh -c "npm install && npm start"
      volumes:
         - .:/app
         - ./docker/scripts:/scripts
      ports:
         - 3000:3000
